#!/usr/bin/env bash
# Install nginx on web-01 server
sudo apt-get update -y
sudo apt upgrade -y
sudo apt-get install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
