#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx start
