#!/usr/bin/env bash
# Install HAProxy and configure the load balancer with 2 web servers

apt-get -y update
apt-get -y install haproxy=1.6.\*
echo "backend web-backend
        balance roundrobin
        server 41056-web-01 3.229.138.221:80 check
        server 41056-web-02 35.153.78.63:80 check" >> /etc/haproxy/haproxy.cfg
echo "frontend http
        bind *:80\
        mode http
        default_backend web-backend" >> /etc/haproxy/haproxy.cfg
service haproxy restart
